name: CI

on:
  push: {}
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
    - uses: earthly/actions-setup@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: earthly +test
      if: github.ref != 'refs/heads/main'
      run: earthly --strict +test

    - name: earthly +push
      if: github.ref == 'refs/heads/main'
      run: earthly --push --secret NUGET_API_KEY= --secret PSGALLERY_API_KEY --strict +all
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}

    - uses: actions/upload-artifact@v3
      with:
        name: Pansies
        path: Modules/Pansies

    - uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: Modules/Pansies-TestResults

    - uses: actions/upload-artifact@v3
      with:
        name: Packages
        path: Modules/Pansies-Packages
